version: "3.9"
services:
  hello-service:
    build: ./services/hello-service
    ports:
      - "3002:3002"
    depends_on:
      - users-service

  users-service:
    build: ./services/users
    ports:
      - "3003:3003"

  # لاحقاً يمكن إضافة auth-service
  # auth-service:
  #   build: ./services/auth-service
  #   ports:
  #     - "3003:3003"
  #   depends_on:
  #     - users-service
